version = 0.1
[default.deploy.parameters]
stack_name = "wild-rydes-async-msg-1"
resolve_s3 = true
s3_prefix = "wild-rydes-async-msg-1"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
